# Generated by Django 2.2.3 on 2019-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'verbose_name_plural': 'ChatMessages'},
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='room',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
